/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class NER */

#ifndef _Included_NER
#define _Included_NER
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NER
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NER_decode
  (JNIEnv *, jobject, jstring){

    std::cout<< "hello" <<std::endl;
}

#ifdef __cplusplus
}
#endif
#endif
